import type { DomainPackSet } from "./workflow-capabilities";

/**
 * Concrete capability contract for the broad Government Decision workflow.
 * The workflow remains deliberately jurisdiction-neutral; jurisdiction-specific
 * rules must come from the uploaded notice and verified official sources.
 */
export const GOVERNMENT_DECISION_DOMAIN_PACK: DomainPackSet = {
  engine: "appeal",
  document: {
    name: "government-decision-document-intelligence",
    acceptedTypes: ["application/pdf", "image/png", "image/jpeg"],
    classifierHints: [
      "agency decision",
      "determination",
      "notice of decision",
      "final agency action",
      "appeal rights",
      "hearing rights",
      "administrative decision",
      "government notice",
    ],
    extractionSchema: [
      "agency",
      "program_or_authority",
      "decision_type",
      "reference_number",
      "decision_date",
      "effective_date",
      "deadline",
      "appeal_path",
      "hearing_instructions",
      "filing_method",
      "recipient_or_appeal_authority",
      "reasons",
      "findings",
      "cited_authority",
      "evidence_referenced",
      "requested_next_action",
      "uncertainties",
    ],
    minConfidence: 0.85,
  },
  deadline: {
    name: "government-decision-deadline-analysis",
    triggeringEvents: ["decision date", "service/receipt date", "effective date"],
    sourcePriority: [
      "explicit deadline in decision notice",
      "explicit filing instruction in decision notice",
      "cited regulation/statute",
      "current official agency appeal page",
      "official court guidance",
    ],
    jurisdictionDependent: true,
    computationRules: [
      "Never infer a universal deadline.",
      "Preserve source date and source text for every computed deadline.",
      "Flag receipt/service-date uncertainty instead of guessing.",
      "Block execution when the appeal period cannot be reliably established.",
    ],
  },
  evidence: {
    name: "government-decision-evidence-analysis",
    evidenceTypes: [
      "decision notice",
      "agency correspondence",
      "application or request",
      "prior submissions",
      "records cited by agency",
      "supporting exhibits",
      "proof of submission or receipt",
      "official source citation",
    ],
    sufficiencyRules: [
      "Every material response ground must point to a source or explicitly remain unresolved.",
      "Agency findings must be distinguished from user assertions.",
      "Cited legal or policy authority must be preserved as a source reference rather than paraphrased as certainty.",
    ],
    contradictionRules: [
      "Decision vs user evidence",
      "Decision date vs receipt/service date",
      "Agency finding vs cited record",
      "Requested relief vs available appeal path",
      "Notice instruction vs external source",
    ],
    missingEvidenceBehavior: "block",
  },
  analysis: {
    name: "government-decision-authority-analysis",
    capabilities: [
      "xray-analysis",
      "timeline-analysis",
      "stress-testing",
      "response-strategy",
      "contradiction-analysis",
    ],
    orderedChecks: [
      "document classification",
      "agency/authority identification",
      "decision posture",
      "deadline and receipt verification",
      "appeal-path verification",
      "finding-to-evidence map",
      "procedural requirement map",
      "contradiction analysis",
      "adversarial stress test",
      "response strategy",
    ],
    riskFactors: [
      "unknown jurisdiction",
      "unknown agency",
      "uncertain receipt date",
      "uncertain finality",
      "deadline ambiguity",
      "missing appeal instructions",
      "missing cited authority",
      "unsupported factual dispute",
      "possible exhaustion requirement",
      "possible judicial-review transition",
    ],
    outputSections: [
      "decision summary",
      "source-grounded findings",
      "deadline",
      "appeal path",
      "procedural requirements",
      "issues and contradictions",
      "evidence checklist",
      "response strategy",
      "uncertainties and blockers",
    ],
  },
  draft: {
    name: "government-decision-response-drafting",
    draftType: "administrative-appeal-response",
    requiredSections: [
      "recipient",
      "reference number",
      "decision identification",
      "requested action",
      "ground-by-ground response",
      "supporting evidence",
      "procedural compliance",
      "signature/contact block",
    ],
    prohibitedUnsupportedClaims: [
      "unstated legal rule",
      "invented deadline",
      "invented agency policy",
      "invented procedural right",
      "guaranteed outcome",
      "unsupported factual assertion",
    ],
    toneRules: [
      "professional",
      "specific",
      "source-grounded",
      "non-confrontational",
      "clear requested relief",
    ],
  },
  validation: {
    name: "government-decision-final-validation",
    factualChecks: [
      "agency name",
      "reference number",
      "decision date",
      "receipt/service date",
      "requested relief",
      "supporting evidence references",
    ],
    requirementChecks: [
      "appeal destination",
      "filing method",
      "deadline",
      "required form",
      "signature",
      "attachments",
      "copies or exhibits",
    ],
    unsupportedAssertionChecks: [
      "legal conclusions",
      "deadline claims",
      "agency-policy claims",
      "factual claims not grounded in supplied evidence",
    ],
    adversarialChecks: [
      "What if the deadline was calculated from receipt rather than decision date?",
      "What if the decision is not final and a different internal review applies?",
      "What if the cited rule conflicts with the current official source?",
      "What if a required form or filing portal is missing?",
      "What if the requested relief is unavailable at this stage?",
    ],
  },
  submission: {
    name: "government-decision-mail-submission",
    methods: ["mail", "certified", "registered"],
    recipientRules: [
      "Recipient must match the decision notice or verified official filing instruction.",
      "A generic agency address must never replace a stated appeal authority without verification.",
      "When electronic filing is the required or preferred method, surface that instruction before allowing mailing.",
    ],
    supportsMailing: true,
    supportsTracking: true,
    proofRequirements: [
      "provider order id",
      "mailing timestamp",
      "tracking state when available",
      "final document hash",
      "recipient record",
      "transaction record",
    ],
  },
};
