export const UNEMPLOYMENT_APPEAL_CAPABILITIES = ["document-classification","fact-extraction","agency-resolution","deadline-verification","appeal-path-verification","evidence-analysis","contradiction-detection","timeline-analysis","adversarial-stress-test","response-strategy","drafting","independent-validation","readiness","human-approval","pricing","deterministic-pdf","submission","mailing","proof"] as const;
export const UNEMPLOYMENT_APPEAL_AUTHORITY_RULES = ["Never infer a universal unemployment appeal deadline.","Never assume the state agency or appeal forum.","Never invent an appeal form, recipient, filing method, hearing rule, or exhaustion requirement.","Treat the decision notice's instructions as primary document evidence and verify them against current official agency authority.","Keep unemployment benefit eligibility, overpayment, employer charge, and second-level review paths distinct.","Never invent employment, wage, separation, or claimant facts."] as const;
export const UNEMPLOYMENT_APPEAL_PRICING = { preparationFee: 24.99, includedResponsePages: 3, responsePagePrice: 0.4, supportingPagePrice: 0.25, standardMail: 5.49, certifiedMail: 12.49, certifiedReturnReceipt: 14.99, registeredMail: 29.99, flatEnvelopeFee: 2.5 } as const;
export const UNEMPLOYMENT_AUTHORITY_SOURCES = [
 {title:"U.S. Department of Labor — Unemployment Insurance", url:"https://oui.doleta.gov/unemploy/", type:"federal"},
 {title:"California EDD — Unemployment Insurance Appeals", url:"https://edd.ca.gov/en/unemployment/appeals/", type:"state-example"},
 {title:"California EDD — Appeal Form DE 1000M", url:"https://edd.ca.gov/siteassets/files/pdf_pub_ctr/de1000m.pdf", type:"state-form-example"},
];
export const UNEMPLOYMENT_APPEAL_GOLD = { workflowId:"unemployment-appeal", title:"Appeal an Unemployment Decision", capabilities:UNEMPLOYMENT_APPEAL_CAPABILITIES, authorityRules:UNEMPLOYMENT_APPEAL_AUTHORITY_RULES, pricing:UNEMPLOYMENT_APPEAL_PRICING, authoritySources:UNEMPLOYMENT_AUTHORITY_SOURCES, lifecycle:"authority" } as const;
