import { createFileRoute } from "@tanstack/react-router";
import { requireAuthenticatedUser, getSupabaseServer } from "@/platform/supabase";
import { uploadDocument } from "@/platform/mailmypdf";

type ProviderConfig = { provider: "anthropic" | "openai" | "gemini"; apiKey: string; model: string; promptOverride?: string | null };
async function resolveProvider() { const base = process.env.MAILMYPDF_CONTROL_PLANE_URL || "https://mailmypdf.com"; const token = process.env.MAILMYPDF_CONTROL_PLANE_TOKEN; if (!token) throw new Error("MailMyPDF control-plane token is not configured."); const response = await fetch(`${base.replace(/\/$/, "")}/api/control-plane/ai`, { method: "POST", headers: { "content-type": "application/json", authorization: `Bearer ${token}` }, body: JSON.stringify({ verticalSlug: "appeal-mail", workflowSlug: "agency-decision-appeal", task: "analysis" }) }); const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(payload?.error || `Control plane error (${response.status}).`); return payload as ProviderConfig; }
function mediaType(file: File) { if (["application/pdf", "image/png", "image/jpeg"].includes(file.type)) return file.type; throw new Error("Agency Decision Appeal accepts PDF, PNG, and JPEG source documents."); }
function s(value: unknown): string { return typeof value === "string" ? value : ""; }

export const Route = createFileRoute("/api/workflows/agency-decision/analyze")({ server: { handlers: { POST: async ({ request }) => {
  try {
    const user = await requireAuthenticatedUser(request); const form = await request.formData(); const file = form.get("document");
    if (!(file instanceof File)) return Response.json({ error: "A source decision is required." }, { status: 400 });
    if (file.size === 0) return Response.json({ error: "The source document is empty." }, { status: 400 });
    if (file.size > 20 * 1024 * 1024) return Response.json({ error: "Source documents must be 20 MB or smaller." }, { status: 413 });
    const provider = await resolveProvider(); if (provider.provider !== "gemini") throw new Error("Agency Decision Appeal is currently configured for Gemini.");
    const sourceDocument = await uploadDocument(file); const bytes = Buffer.from(await file.arrayBuffer()).toString("base64");
    const prompt = provider.promptOverride || ["You are the authority-first analyst for an administrative agency decision appeal workflow.","Return strict JSON only. Extract only what is supported by the uploaded decision.","Never invent deadlines, agency procedures, recipient addresses, exhaustion requirements, review levels, forms, filing methods, legal rules, facts, or outcomes.","Separate document facts from procedural conclusions. A date appearing in the document is not a verified procedural deadline unless the document explicitly says so.","Return this shape:",'{"summary":"","issuer":"","jurisdiction":"","referenceNumber":"","decisionDate":"","deadline":"","deadlineStatus":"extracted|verified|unverified","appealInstructions":"","findings":[],"citedAuthority":[],"disputedFacts":[],"evidenceMentioned":[],"evidenceGaps":[],"contradictions":[],"uncertainties":[],"authoritySources":[{"claim":"","sourceType":"document|agency|court|statute|regulation|rule|other","sourceUrl":"","sourceTitle":"","jurisdiction":"","effectiveDate":"","verificationState":"verified|partially_verified|unverified|conflicting","notes":""}],"confidence":"high|medium|low"}',"Use empty strings and arrays for unknown values."].join("\n");
    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(provider.model)}:generateContent?key=${encodeURIComponent(provider.apiKey)}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ contents: [{ role: "user", parts: [{ inlineData: { mimeType: mediaType(file), data: bytes } }, { text: prompt }] }], generationConfig: { responseMimeType: "application/json", temperature: 0.1 } }) });
    const body = await response.json().catch(() => null) as any; if (!response.ok) throw new Error(body?.error?.message || `Gemini analysis failed (${response.status}).`);
    const text = body?.candidates?.[0]?.content?.parts?.map((part: { text?: string }) => part.text || "").join("").trim(); if (!text) throw new Error("Gemini returned no analysis.");
    const analysis = JSON.parse(text) as Record<string, unknown>; const now = new Date().toISOString(); const appealId = crypto.randomUUID();
    const decision = { id: crypto.randomUUID(), type: "agency_decision", documentId: sourceDocument.id, documentFilename: file.name, agency: s(analysis.issuer), jurisdiction: s(analysis.jurisdiction), referenceNumber: s(analysis.referenceNumber), decisionDate: s(analysis.decisionDate), deadline: s(analysis.deadline) ? { date: s(analysis.deadline), status: s(analysis.deadlineStatus) || "unverified", source: "extracted" } : undefined, findings: Array.isArray(analysis.findings) ? analysis.findings : [], citedAuthority: Array.isArray(analysis.citedAuthority) ? analysis.citedAuthority : [], disputedFacts: Array.isArray(analysis.disputedFacts) ? analysis.disputedFacts : [], evidenceGaps: Array.isArray(analysis.evidenceGaps) ? analysis.evidenceGaps : [], contradictions: Array.isArray(analysis.contradictions) ? analysis.contradictions : [], authoritySources: Array.isArray(analysis.authoritySources) ? analysis.authoritySources : [], uncertainties: Array.isArray(analysis.uncertainties) ? analysis.uncertainties : [], appealInstructions: s(analysis.appealInstructions), extractedAt: now };
    const supabase = await getSupabaseServer(); const { error } = await supabase.from("appeals").insert({ id: appealId, user_id: user.id, workflow_id: "agency-decision-appeal", status: "in_progress", decision, grounds: [], evidence: [{ id: crypto.randomUUID(), type: "document", label: file.name, documentId: sourceDocument.id, uploadedAt: now }], arguments: [], draft: "", review: null, packet: null, proof: null, timeline: [], version: 1, created_at: now, updated_at: now });
    if (error) throw new Error(`Unable to save appeal: ${error.message}`);
    return Response.json({ ok: true, appealId, documentId: sourceDocument.id, analysis });
  } catch (error) { const message = error instanceof Error ? error.message : "Unable to analyze agency decision."; const status = /authentication|required|token/i.test(message) ? 401 : 502; return Response.json({ error: message }, { status }); }
} } } });
