import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { APPEALS_COUNCIL_PRICING } from "@/domain/appeals-council-gold";

export const Route = createFileRoute("/workflows/appeals-council")({
  head: () => ({ meta: [
    { title: "Request Appeals Council Review — Authority-First | Appeal Mail" },
    { name: "description", content: "Analyze an SSA hearing decision, verify Appeals Council review requirements, map evidence and procedural issues, and prepare a human-reviewed response with transparent packet pricing." },
    { property: "og:title", content: "Request Appeals Council Review" },
    { property: "og:description", content: "SSA Appeals Council review analysis with deadline discipline, evidence mapping, Gemini drafting, validation, and documented mailing proof." },
  ], links: [{ rel: "canonical", href: "/workflows/appeals-council" }] }),
  component: AppealsCouncilPage,
});

function AppealsCouncilPage() {
  const [file,setFile]=useState<File|null>(null); const [status,setStatus]=useState(""); const [result,setResult]=useState<any>(null);
  async function analyze(){ if(!file)return; setStatus("Analyzing the hearing decision and checking the Appeals Council path against SSA authority…"); const form=new FormData();form.set("document",file); try{const r=await fetch("/api/workflows/appeals-council/analyze",{method:"POST",body:form});const p=await r.json();if(!r.ok)throw new Error(p.error||"Unable to analyze the decision.");setResult(p);setStatus("Analysis complete. Review the authority, evidence, and unresolved items before drafting.");}catch(e){setStatus(e instanceof Error?e.message:"Unable to analyze the decision.");}}
  return <main className="mx-auto max-w-6xl px-6 py-12">
    <section className="rounded-3xl bg-slate-950 p-8 text-white shadow-xl">
      <p className="text-sm font-semibold uppercase tracking-[0.22em] text-slate-300">SSA Appeals Council • Authority-first</p>
      <h1 className="mt-4 max-w-4xl text-4xl font-bold tracking-tight md:text-6xl">Request Appeals Council Review</h1>
      <p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">Start with the Administrative Law Judge hearing decision or dismissal. The workflow separates what SSA actually decided from procedural rules that must be verified, analyzes the record and additional evidence, stress-tests the response, and requires your approval before mailing.</p>
      <div className="mt-8 grid gap-4 md:grid-cols-3">{[["Authority raised","Current SSA guidance, the notice, HA-520 instructions, and governing CFR provisions are treated as the controlling sources."],["Evidence discipline","New evidence, missing support, contradictions, and record references are surfaced without inventing medical or vocational facts."],["Transparent pricing","Preparation, response sheets, supporting sheets, mailing method, and any packet surcharge are shown before payment."]].map(([a,c])=><div key={a} className="rounded-2xl border border-white/10 bg-white/5 p-5"><h2 className="font-semibold">{a}</h2><p className="mt-2 text-sm leading-6 text-slate-300">{c}</p></div>)}</div>
    </section>
    <section className="mt-10 grid gap-8 lg:grid-cols-[1.1fr_.9fr]">
      <div className="rounded-3xl border border-slate-200 bg-white p-7"><h2 className="text-2xl font-semibold">What we analyze</h2><ol className="mt-6 space-y-4">{["Identify the ALJ action, claimant/claim reference, decision date, findings, reasons, and instructions.","Verify the Appeals Council review path and deadline against the notice and current SSA sources.","Separate supported grounds from disputed facts, record gaps, and unsupported assumptions.","Analyze additional evidence and whether the record supports explaining why it matters.","Draft, independently validate, and require explicit human approval before payment and mailing."].map((x,i)=><li key={x} className="flex gap-4"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-slate-900 text-sm font-bold text-white">{i+1}</span><span className="leading-7 text-slate-700">{x}</span></li>)}</ol></div>
      <div className="rounded-3xl border border-slate-200 bg-slate-50 p-7"><h2 className="text-2xl font-semibold">Start with your hearing decision</h2><p className="mt-3 text-sm leading-6 text-slate-600">Starting price: <strong>${APPEALS_COUNCIL_PRICING.preparationFee.toFixed(2)}</strong> plus mailing, assuming {APPEALS_COUNCIL_PRICING.includedResponsePages} response pages and no supporting-document sheets. The exact price is calculated from the approved packet.</p><input className="mt-6 block w-full rounded-xl border border-slate-300 bg-white p-3 text-sm" type="file" accept="application/pdf,image/png,image/jpeg" onChange={e=>setFile(e.target.files?.[0]||null)}/><button className="mt-4 w-full rounded-xl bg-slate-900 px-5 py-3 font-semibold text-white disabled:opacity-40" disabled={!file} onClick={analyze}>Analyze hearing decision</button>{status&&<p className="mt-4 text-sm text-slate-600">{status}</p>}{result&&<div className="mt-6 rounded-2xl bg-white p-5"><h3 className="font-semibold">Decision snapshot</h3><dl className="mt-3 space-y-2 text-sm"><div><dt className="inline font-medium">Issuer: </dt><dd className="inline">{result.analysis?.issuer||"Not identified"}</dd></div><div><dt className="inline font-medium">Decision date: </dt><dd className="inline">{result.analysis?.decisionDate||"Not identified"}</dd></div><div><dt className="inline font-medium">Deadline status: </dt><dd className="inline">{result.analysis?.deadlineStatus||"unverified"}</dd></div></dl></div>}</div>
    </section>
    <section className="mt-10 rounded-3xl border border-slate-200 bg-white p-7"><h2 className="text-2xl font-semibold">Transparent pricing</h2><div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[["Preparation",`$${APPEALS_COUNCIL_PRICING.preparationFee.toFixed(2)}`],["Included response",`${APPEALS_COUNCIL_PRICING.includedResponsePages} pages"],["Extra response",`$${APPEALS_COUNCIL_PRICING.responsePagePrice.toFixed(2)}/sheet`],["Supporting evidence",`$${APPEALS_COUNCIL_PRICING.supportingPagePrice.toFixed(2)}/sheet`],["Standard mail",`$${APPEALS_COUNCIL_PRICING.standardMail.toFixed(2)}`],["Certified",`$${APPEALS_COUNCIL_PRICING.certifiedMail.toFixed(2)}`],["Certified + return receipt",`$${APPEALS_COUNCIL_PRICING.certifiedReturnReceipt.toFixed(2)}`],["Flat packet surcharge",`$${APPEALS_COUNCIL_PRICING.flatEnvelopeFee.toFixed(2)} when required`]].map(([a,b])=><div key={a} className="rounded-2xl bg-slate-50 p-4"><div className="text-sm text-slate-500">{a}</div><div className="mt-1 font-semibold">{b}</div></div>)}</div><p className="mt-6 text-sm leading-7 text-slate-600">The final price is based on the approved physical packet. Evidence pages are not silently bundled into the preparation fee.</p></section>
    <p className="mt-10 text-sm text-slate-500">Appeal Mail is not a law firm and does not provide legal advice. SSA-specific rules are verified against current authoritative sources before procedural conclusions are presented.</p>
  </main>;
}
