import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { EDD_APPEAL_PRICING, EDD_APPEAL_AUTHORITY_SOURCES } from "@/domain/edd-appeal-gold";

export const Route = createFileRoute("/workflows/edd-appeal")({
  head: () => ({ meta: [
    { title: "Appeal an EDD Decision — Authority-First | Appeal Mail" },
    { name: "description", content: "Analyze a California EDD decision, verify the correct appeal path and deadline, map evidence, prepare a human-reviewed response, and mail it with transparent pricing." },
    { property: "og:title", content: "Appeal an EDD Decision" },
    { property: "og:description", content: "Authority-first EDD appeal analysis with current EDD sources, evidence mapping, Gemini drafting, validation, pricing, and mailing proof." },
  ], links: [{ rel: "canonical", href: "/workflows/edd-appeal" }] }),
  component: EddPage,
});

function EddPage() {
  const [file,setFile]=useState<File|null>(null); const [status,setStatus]=useState(""); const [result,setResult]=useState<any>(null);
  async function analyze(){if(!file)return;setStatus("Analyzing the EDD notice and checking the appeal path against current EDD authority…");const form=new FormData();form.set("document",file);try{const r=await fetch("/api/workflows/edd-appeal/analyze",{method:"POST",body:form});const p=await r.json();if(!r.ok)throw new Error(p.error||"Unable to analyze the EDD notice.");setResult(p);setStatus("Analysis complete. Review the decision, authority status, evidence gaps, and exact price basis.");}catch(e){setStatus(e instanceof Error?e.message:"Unable to analyze the EDD notice.");}}
  return <main className="mx-auto max-w-6xl px-6 py-12">
    <section className="rounded-3xl bg-slate-950 p-8 text-white shadow-xl"><p className="text-sm font-semibold uppercase tracking-[0.22em] text-slate-300">California EDD • Authority-first appeal</p><h1 className="mt-4 max-w-4xl text-4xl font-bold tracking-tight md:text-6xl">Appeal an EDD Decision</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">Upload an EDD unemployment decision, overpayment notice, or related determination and build a source-grounded response. The workflow verifies the procedure it can verify, flags what still needs human confirmation, and never invents eligibility or procedural facts.</p><div className="mt-8 grid gap-4 md:grid-cols-3">{[["Authority raised","Current EDD and CUIAB sources are separated from the facts in your notice."],["Evidence aware","We map disputed facts, missing records, contradictions, and the documents you want EDD to review."],["Transparent price","Preparation, response sheets, supporting sheets, and mailing service are disclosed before payment."]].map(([a,c])=><div key={a} className="rounded-2xl border border-white/10 bg-white/5 p-5"><h2 className="font-semibold">{a}</h2><p className="mt-2 text-sm leading-6 text-slate-300">{c}</p></div>)}</div></section>
    <section className="mt-10 grid gap-8 lg:grid-cols-[1.1fr_.9fr]">
      <div className="rounded-3xl border border-slate-200 bg-white p-7"><h2 className="text-2xl font-semibold">What the workflow checks</h2><ol className="mt-6 space-y-4">{["Classify the EDD matter and extract notice type, dates, reference numbers, findings, and instructions.","Verify the applicable appeal path and timing from the notice and current EDD sources.","Separate claimant/employer facts from source facts and unresolved questions.","Map evidence, contradictions, and requested relief, then stress-test the response.","Draft, independently validate, require human approval, calculate the packet price, and mail only after payment."].map((x,i)=><li key={x} className="flex gap-4"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-slate-900 text-sm font-bold text-white">{i+1}</span><span className="leading-7 text-slate-700">{x}</span></li>)}</ol></div>
      <div className="rounded-3xl border border-slate-200 bg-slate-50 p-7"><h2 className="text-2xl font-semibold">Start with the notice</h2><p className="mt-3 text-sm leading-6 text-slate-600">Starting price: <strong>${EDD_APPEAL_PRICING.preparationFee.toFixed(2)}</strong> for a {EDD_APPEAL_PRICING.includedResponsePages}-page response, before mailing and supporting-document sheets. Exact price is calculated from the approved packet.</p><input className="mt-6 block w-full rounded-xl border border-slate-300 bg-white p-3 text-sm" type="file" accept="application/pdf,image/png,image/jpeg" onChange={e=>setFile(e.target.files?.[0]||null)}/><button className="mt-4 w-full rounded-xl bg-slate-900 px-5 py-3 font-semibold text-white disabled:opacity-40" disabled={!file} onClick={analyze}>Analyze EDD notice</button>{status&&<p className="mt-4 text-sm text-slate-600">{status}</p>}{result&&<div className="mt-6 rounded-2xl bg-white p-5"><h3 className="font-semibold">Decision snapshot</h3><dl className="mt-3 space-y-2 text-sm"><div><dt className="inline font-medium">Matter type: </dt><dd className="inline">{result.analysis?.matterType||"Not identified"}</dd></div><div><dt className="inline font-medium">Notice date: </dt><dd className="inline">{result.analysis?.noticeDate||"Not identified"}</dd></div><div><dt className="inline font-medium">Deadline status: </dt><dd className="inline">{result.analysis?.deadlineStatus||"unverified"}</dd></div></dl></div>}</div>
    </section>
    <section className="mt-10 rounded-3xl border border-slate-200 bg-white p-7"><h2 className="text-2xl font-semibold">Transparent pricing</h2><div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[["Preparation",`$${EDD_APPEAL_PRICING.preparationFee.toFixed(2)}`],["Included response",`${EDD_APPEAL_PRICING.includedResponsePages} pages`],["Extra response",`$${EDD_APPEAL_PRICING.responsePagePrice.toFixed(2)}/sheet`],["Supporting documents",`$${EDD_APPEAL_PRICING.supportingPagePrice.toFixed(2)}/sheet`],["Standard mail",`$${EDD_APPEAL_PRICING.standardMail.toFixed(2)}`],["Certified",`$${EDD_APPEAL_PRICING.certifiedMail.toFixed(2)}`],["Certified + return receipt",`$${EDD_APPEAL_PRICING.certifiedReturnReceipt.toFixed(2)}`],["Flat packet surcharge",`$${EDD_APPEAL_PRICING.flatEnvelopeFee.toFixed(2)} when required`]].map(([a,b])=><div key={a} className="rounded-2xl bg-slate-50 p-4"><div className="text-sm text-slate-500">{a}</div><div className="mt-1 font-semibold">{b}</div></div>)}</div><p className="mt-6 text-sm leading-7 text-slate-600">The exact payable amount is based on the final approved physical packet. Supporting pages are never silently bundled into the base preparation fee.</p></section>
    <section className="mt-10 rounded-3xl border border-slate-200 bg-white p-7"><h2 className="text-2xl font-semibold">Authority sources</h2><div className="mt-5 space-y-3">{EDD_APPEAL_AUTHORITY_SOURCES.map(s=><a className="block rounded-xl bg-slate-50 p-4 text-sm font-medium text-slate-800 hover:bg-slate-100" href={s.url} target="_blank" rel="noreferrer" key={s.url}>{s.name}</a>)}</div></section>
    <p className="mt-10 text-sm text-slate-500">Appeal Mail is not a law firm and does not provide legal advice. EDD timing, forms, filing destinations, and matter-specific requirements are verified from the controlling notice and current authoritative sources.</p>
  </main>;
}
