import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";

export const Route = createFileRoute("/workflows/social-security-overpayment")({ head: () => ({ meta: [
  { title: "Appeal a Social Security Overpayment — Authority-First | Appeal Mail" },
  { name: "description", content: "Analyze a Social Security overpayment notice, distinguish reconsideration, waiver and repayment-rate options, identify evidence gaps, and prepare a human-reviewed response with transparent pricing." },
  { property: "og:title", content: "Appeal a Social Security Overpayment" },
  { property: "og:description", content: "Authority-first overpayment analysis with SSA-source verification, deadline discipline, evidence mapping, Gemini drafting, transparent pricing, and mailing proof." },
], links: [{ rel: "canonical", href: "/workflows/social-security-overpayment" }] }), component: SocialSecurityOverpaymentPage });

function SocialSecurityOverpaymentPage() {
  const [file,setFile]=useState<File|null>(null); const [status,setStatus]=useState(""); const [result,setResult]=useState<any>(null);
  async function analyze(){ if(!file)return; setStatus("Analyzing the overpayment notice and separating reconsideration, waiver, and repayment issues…"); const f=new FormData();f.set("document",file); try{const r=await fetch("/api/workflows/social-security-overpayment/analyze",{method:"POST",body:f});const p=await r.json();if(!r.ok)throw new Error(p.error||"Unable to analyze notice.");setResult(p);setStatus("Analysis complete. Review the authority record, evidence gaps, and unresolved items before drafting.");}catch(e){setStatus(e instanceof Error?e.message:"Unable to analyze notice.");}}
  return <main className="mx-auto max-w-6xl px-6 py-12">
    <section className="rounded-3xl bg-slate-950 p-8 text-white shadow-xl"><p className="text-sm font-semibold uppercase tracking-[0.22em] text-slate-300">Authority-first Social Security overpayment workflow</p><h1 className="mt-4 max-w-4xl text-4xl font-bold md:text-6xl">Appeal a Social Security Overpayment</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">Understand whether your notice calls for reconsideration, waiver, or a repayment-rate request. The workflow grounds procedural claims in current SSA sources and never invents the amount, facts, deadline, or filing path.</p><div className="mt-8 grid gap-4 md:grid-cols-3">{[["Separate the remedy","Reconsideration, waiver, and repayment-rate requests are analyzed as different paths."],["Authority raised","SSA forms, guidance, and applicable program rules are surfaced with verification status."],["Transparent price","Preparation, response sheets, supporting sheets, and mailing are priced before payment."]].map(([a,c])=><div key={a} className="rounded-2xl border border-white/10 bg-white/5 p-5"><h2 className="font-semibold">{a}</h2><p className="mt-2 text-sm leading-6 text-slate-300">{c}</p></div>)}</div></section>
    <section className="mt-10 grid gap-8 lg:grid-cols-[1.1fr_.9fr]">
      <div className="rounded-3xl border border-slate-200 bg-white p-7"><h2 className="text-2xl font-semibold">What we analyze</h2><ol className="mt-6 space-y-4 text-slate-700">{["Extract the overpayment notice, amount, period, stated reason, dates, instructions, and cited authority.","Determine whether the record supports reconsideration, waiver, repayment-rate relief, or more than one route.","Check procedural timing and source support without promoting generic rules to universal instructions.","Map evidence, contradictions, fault assertions, hardship support, and disputed amount calculations.","Draft and independently validate a response before explicit human approval and payment."].map((x,i)=><li key={x} className="flex gap-4"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-slate-900 text-sm font-bold text-white">{i+1}</span><span>{x}</span></li>)}</ol></div>
      <div className="rounded-3xl border border-slate-200 bg-slate-50 p-7"><h2 className="text-2xl font-semibold">Start with the overpayment notice</h2><p className="mt-3 text-sm leading-6 text-slate-600">Starting price: <strong>$27.99</strong> for a 3-page response, no supporting sheets, and standard mailing. Exact price comes from the final approved packet.</p><input className="mt-6 block w-full rounded-xl border border-slate-300 bg-white p-3 text-sm" type="file" accept="application/pdf,image/png,image/jpeg" onChange={e=>setFile(e.target.files?.[0]||null)}/><button className="mt-4 w-full rounded-xl bg-slate-900 px-5 py-3 font-semibold text-white disabled:opacity-40" disabled={!file} onClick={analyze}>Analyze overpayment notice</button>{status&&<p className="mt-4 text-sm text-slate-600">{status}</p>}{result&&<div className="mt-6 rounded-2xl bg-white p-5"><h3 className="font-semibold">Notice snapshot</h3><dl className="mt-3 space-y-2 text-sm"><div><dt className="inline font-medium">Program: </dt><dd className="inline">{result.analysis?.program||"Not identified"}</dd></div><div><dt className="inline font-medium">Amount: </dt><dd className="inline">{result.analysis?.overpaymentAmount||"Not identified"}</dd></div><div><dt className="inline font-medium">Notice date: </dt><dd className="inline">{result.analysis?.noticeDate||"Not identified"}</dd></div><div><dt className="inline font-medium">Route: </dt><dd className="inline">{result.analysis?.routeRecommendation||"Needs review"}</dd></div></dl></div>}</div>
    </section>
    <section className="mt-10 rounded-3xl border border-slate-200 bg-white p-7"><h2 className="text-2xl font-semibold">Transparent pricing</h2><div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[["Preparation","$27.99"],["Included response","3 pages"],["Extra response","$0.40/sheet"],["Supporting evidence","$0.25/sheet"],["Standard mail","$5.49"],["Certified","$12.49"],["Certified + return receipt","$14.99"],["Registered","$29.99"]].map(([a,b])=><div key={a} className="rounded-2xl bg-slate-50 p-4"><div className="text-sm text-slate-500">{a}</div><div className="mt-1 font-semibold">{b}</div></div>)}</div><p className="mt-6 text-sm leading-7 text-slate-600">Physical sheet count controls variable printing cost. Supporting records are not silently bundled. You see the exact payable amount before checkout.</p></section>
    <p className="mt-10 text-sm text-slate-500">Appeal Mail is not a law firm and does not provide legal advice. Financial hardship, fault, overpayment amount, and other case facts must come from your records.</p>
  </main>;
}
