import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { SOCIAL_SECURITY_RECONSIDERATION_PRICING } from "@/domain/social-security-reconsideration-gold";

export const Route = createFileRoute("/workflows/social-security-reconsideration")({ head:()=>({meta:[{title:"Social Security Reconsideration — Authority-First | Appeal Mail"},{name:"description",content:"Prepare a Social Security reconsideration request using the actual SSA notice, current SSA authority, evidence mapping, transparent page-based pricing, and human approval before mailing."},{property:"og:title",content:"Social Security Reconsideration"},{property:"og:description",content:"Authority-first SSA reconsideration workflow with deadline verification, evidence analysis, Gemini drafting, transparent pricing, and proof-backed mailing."}],links:[{rel:"canonical",href:"/workflows/social-security-reconsideration"}]}),component:SocialSecurityReconsiderationPage});

function SocialSecurityReconsiderationPage(){
 const [file,setFile]=useState<File|null>(null); const [status,setStatus]=useState(""); const [result,setResult]=useState<any>(null);
 async function analyze(){if(!file)return;setStatus("Analyzing the SSA decision against current SSA authority…");const form=new FormData();form.set("document",file);try{const response=await fetch("/api/workflows/social-security-reconsideration/analyze",{method:"POST",body:form});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Unable to analyze the decision.");setResult(payload);setStatus("Analysis complete. Review authority, evidence gaps, deadline status, and price basis.");}catch(error){setStatus(error instanceof Error?error.message:"Unable to analyze the decision.");}}
 return <main className="mx-auto max-w-6xl px-6 py-12">
  <section className="rounded-3xl bg-slate-950 p-8 text-white shadow-xl"><p className="text-sm font-semibold uppercase tracking-[0.22em] text-slate-300">Authority-first SSA appeal</p><h1 className="mt-4 max-w-4xl text-4xl font-bold tracking-tight md:text-6xl">Request Social Security Reconsideration</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">We analyze the SSA notice, verify the applicable reconsideration path and timing from current SSA authority, organize the record, expose evidence gaps, and prepare a response you approve before it is mailed.</p><div className="mt-8 grid gap-4 md:grid-cols-3">{[["SSA authority","The notice and current SSA sources control procedural conclusions."],["Evidence integrity","Medical, vocational, and factual claims stay tied to the supplied record."],["Transparent pricing","Preparation, response sheets, supporting sheets, and mailing are shown separately."]].map(([title,copy])=><div key={title} className="rounded-2xl border border-white/10 bg-white/5 p-5"><h2 className="font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-300">{copy}</p></div>)}</div></section>
  <section className="mt-10 grid gap-8 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-3xl border border-slate-200 bg-white p-7"><h2 className="text-2xl font-semibold">What the Gold workflow checks</h2><ol className="mt-6 space-y-4">{["Classify the SSA notice and extract findings, dates, references, instructions, and cited authority.","Determine whether the matter is disability or non-medical and verify the applicable reconsideration path.","Calculate timing from receipt rules and authoritative SSA guidance rather than guessing from the notice date.","Map evidence, contradictions, disputed findings, and missing support before drafting.","Independently validate the response and require your approval before payment and mailing."].map((x,i)=><li key={x} className="flex gap-4"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-slate-900 text-sm font-bold text-white">{i+1}</span><span className="leading-7 text-slate-700">{x}</span></li>)}</ol></div><div className="rounded-3xl border border-slate-200 bg-slate-50 p-7"><h2 className="text-2xl font-semibold">Start with your SSA notice</h2><p className="mt-3 text-sm leading-6 text-slate-600">Starting price: <strong>${SOCIAL_SECURITY_RECONSIDERATION_PRICING.preparationFee.toFixed(2)}</strong> for a 4-sheet response, before supporting-document sheets and mailing.</p><input className="mt-6 block w-full rounded-xl border border-slate-300 bg-white p-3 text-sm" type="file" accept="application/pdf,image/png,image/jpeg" onChange={(e)=>setFile(e.target.files?.[0]||null)}/><button className="mt-4 w-full rounded-xl bg-slate-900 px-5 py-3 font-semibold text-white disabled:opacity-40" disabled={!file} onClick={analyze}>Analyze SSA decision</button>{status&&<p className="mt-4 text-sm text-slate-600">{status}</p>}{result&&<div className="mt-6 rounded-2xl bg-white p-5"><h3 className="font-semibold">Authority snapshot</h3><dl className="mt-3 space-y-2 text-sm"><div><dt className="inline font-medium">Decision type: </dt><dd className="inline">{result.analysis?.decisionType||result.analysis?.issuer||"Not identified"}</dd></div><div><dt className="inline font-medium">Decision date: </dt><dd className="inline">{result.analysis?.decisionDate||"Not identified"}</dd></div><div><dt className="inline font-medium">Deadline status: </dt><dd className="inline">{result.analysis?.deadlineStatus||"unverified"}</dd></div></dl></div>}</div></section>
  <section className="mt-10 rounded-3xl border border-slate-200 bg-white p-7"><h2 className="text-2xl font-semibold">Transparent pricing</h2><div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[["Preparation",`$${SOCIAL_SECURITY_RECONSIDERATION_PRICING.preparationFee.toFixed(2)}`],["Included response","4 sheets"],["Extra response",`$${SOCIAL_SECURITY_RECONSIDERATION_PRICING.responsePagePrice.toFixed(2)}/sheet`],["Supporting evidence",`$${SOCIAL_SECURITY_RECONSIDERATION_PRICING.supportingPagePrice.toFixed(2)}/sheet`],["Standard mail",`$${SOCIAL_SECURITY_RECONSIDERATION_PRICING.standardMail.toFixed(2)}`],["Certified",`$${SOCIAL_SECURITY_RECONSIDERATION_PRICING.certifiedMail.toFixed(2)}`],["Certified + receipt",`$${SOCIAL_SECURITY_RECONSIDERATION_PRICING.certifiedReturnReceipt.toFixed(2)}`],["Large packet",`+$${SOCIAL_SECURITY_RECONSIDERATION_PRICING.largePacketFee.toFixed(2)} when required`]].map(([a,b])=><div key={a} className="rounded-2xl bg-slate-50 p-4"><div className="text-sm text-slate-500">{a}</div><div className="mt-1 font-semibold">{b}</div></div>)}</div><p className="mt-6 text-sm leading-7 text-slate-600">The final total is calculated from the approved response and supporting-document sheet count. We do not silently bundle evidence pages into the preparation fee.</p></section>
  <p className="mt-10 text-sm text-slate-500">Appeal Mail is not a law firm and does not provide legal advice. SSA rules and notice-specific instructions control.</p>
 </main>;
}
