import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { UNEMPLOYMENT_APPEAL_PRICING } from "@/domain/unemployment-appeal-gold";

export const Route = createFileRoute("/workflows/unemployment-appeal")({
  head: () => ({ meta: [
    { title: "Appeal an Unemployment Decision — Authority-First | Appeal Mail" },
    { name: "description", content: "Analyze an unemployment determination, verify the applicable agency appeal path and deadline from official sources, identify evidence gaps, and prepare a human-reviewed response with transparent packet pricing." },
    { property: "og:title", content: "Appeal an Unemployment Decision" },
    { property: "og:description", content: "Authority-first unemployment appeal analysis with deadline discipline, evidence mapping, Gemini drafting, validation, and documented mailing proof." },
  ], links: [{ rel: "canonical", href: "/workflows/unemployment-appeal" }] }),
  component: UnemploymentAppealPage,
});

function UnemploymentAppealPage() {
  const [file,setFile]=useState<File|null>(null); const [status,setStatus]=useState(""); const [result,setResult]=useState<any>(null);
  async function analyze(){ if(!file)return; setStatus("Analyzing the unemployment decision and separating notice facts from jurisdiction-specific procedure…"); const form=new FormData(); form.set("document",file); try{const r=await fetch("/api/workflows/unemployment-appeal/analyze",{method:"POST",body:form});const p=await r.json();if(!r.ok)throw new Error(p.error||"Unable to analyze the decision.");setResult(p);setStatus("Analysis complete. Review the agency, deadline, evidence gaps, and unresolved authority items before drafting.");}catch(e){setStatus(e instanceof Error?e.message:"Unable to analyze the decision.");}}
  return <main className="mx-auto max-w-6xl px-6 py-12">
    <section className="rounded-3xl bg-slate-950 p-8 text-white shadow-xl"><p className="text-sm font-semibold uppercase tracking-[0.22em] text-slate-300">Unemployment • Authority-first</p><h1 className="mt-4 max-w-4xl text-4xl font-bold tracking-tight md:text-6xl">Appeal an Unemployment Decision</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">Analyze what the agency decided, identify the actual appeal path, verify timing and filing instructions from current official sources, organize supporting records, and prepare a response you approve before it is mailed.</p><div className="mt-8 grid gap-4 md:grid-cols-3">{[["Authority raised","State unemployment procedures vary. The decision notice and current official agency guidance control; unsupported rules remain unresolved."],["Evidence-aware","Employment, wage, separation, claimant statements, notices, and supporting records are analyzed without inventing facts."],["Transparent price","Preparation, response sheets, evidence sheets, mailing service, and packet surcharges are shown before payment."]].map(([a,c])=><div key={a} className="rounded-2xl border border-white/10 bg-white/5 p-5"><h2 className="font-semibold">{a}</h2><p className="mt-2 text-sm leading-6 text-slate-300">{c}</p></div>)}</div></section>
    <section className="mt-10 grid gap-8 lg:grid-cols-[1.1fr_.9fr]">
      <div className="rounded-3xl border border-slate-200 bg-white p-7"><h2 className="text-2xl font-semibold">What we analyze</h2><ol className="mt-6 space-y-4">{["Identify the state/agency, notice type, decision date, reference number, findings, reasons, and instructions.","Verify the apparent appeal deadline and filing path from the notice and current official agency sources.","Map disputed employment facts, wage/earnings issues, separation issues, procedural facts, contradictions, and evidence gaps.","Stress-test the response and independently validate dates, references, recipient instructions, and unsupported claims.","Require explicit human approval before final pricing, payment, and mailing."].map((x,i)=><li key={x} className="flex gap-4"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-slate-900 text-sm font-bold text-white">{i+1}</span><span className="leading-7 text-slate-700">{x}</span></li>)}</ol></div>
      <div className="rounded-3xl border border-slate-200 bg-slate-50 p-7"><h2 className="text-2xl font-semibold">Start with your decision</h2><p className="mt-3 text-sm leading-6 text-slate-600">Starting price: <strong>${UNEMPLOYMENT_APPEAL_PRICING.preparationFee.toFixed(2)}</strong> plus mailing, assuming {UNEMPLOYMENT_APPEAL_PRICING.includedResponsePages} response pages and no supporting-document sheets. The exact price is calculated from the approved packet.</p><input className="mt-6 block w-full rounded-xl border border-slate-300 bg-white p-3 text-sm" type="file" accept="application/pdf,image/png,image/jpeg" onChange={e=>setFile(e.target.files?.[0]||null)}/><button className="mt-4 w-full rounded-xl bg-slate-900 px-5 py-3 font-semibold text-white disabled:opacity-40" disabled={!file} onClick={analyze}>Analyze unemployment decision</button>{status&&<p className="mt-4 text-sm text-slate-600">{status}</p>}{result&&<div className="mt-6 rounded-2xl bg-white p-5"><h3 className="font-semibold">Decision snapshot</h3><dl className="mt-3 space-y-2 text-sm"><div><dt className="inline font-medium">Agency: </dt><dd className="inline">{result.analysis?.issuer||"Not identified"}</dd></div><div><dt className="inline font-medium">Jurisdiction: </dt><dd className="inline">{result.analysis?.jurisdiction||"Not identified"}</dd></div><div><dt className="inline font-medium">Deadline status: </dt><dd className="inline">{result.analysis?.deadlineStatus||"unverified"}</dd></div></dl></div>}</div>
    </section>
    <section className="mt-10 rounded-3xl border border-slate-200 bg-white p-7"><h2 className="text-2xl font-semibold">Transparent pricing</h2><div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[["Preparation",`$${UNEMPLOYMENT_APPEAL_PRICING.preparationFee.toFixed(2)}`],["Included response",`${UNEMPLOYMENT_APPEAL_PRICING.includedResponsePages} pages`],["Extra response",`$${UNEMPLOYMENT_APPEAL_PRICING.responsePagePrice.toFixed(2)}/sheet`],["Supporting evidence",`$${UNEMPLOYMENT_APPEAL_PRICING.supportingPagePrice.toFixed(2)}/sheet`],["Standard mail",`$${UNEMPLOYMENT_APPEAL_PRICING.standardMail.toFixed(2)}`],["Certified",`$${UNEMPLOYMENT_APPEAL_PRICING.certifiedMail.toFixed(2)}`],["Certified + return receipt",`$${UNEMPLOYMENT_APPEAL_PRICING.certifiedReturnReceipt.toFixed(2)}`],["Flat packet surcharge",`$${UNEMPLOYMENT_APPEAL_PRICING.flatEnvelopeFee.toFixed(2)} when required`]].map(([a,b])=><div key={a} className="rounded-2xl bg-slate-50 p-4"><div className="text-sm text-slate-500">{a}</div><div className="mt-1 font-semibold">{b}</div></div>)}</div><p className="mt-6 text-sm leading-7 text-slate-600">The final price is based on the approved physical packet. Supporting evidence is priced explicitly rather than silently bundled.</p></section>
    <p className="mt-10 text-sm text-slate-500">Appeal Mail is not a law firm and does not provide legal advice. Unemployment procedures are agency- and jurisdiction-specific and are verified against current authoritative sources before procedural conclusions are presented.</p>
  </main>;
}
