import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { WORKERS_COMP_APPEAL_PRICING } from "@/domain/workers-comp-appeal-gold";

export const Route = createFileRoute("/workflows/workers-comp-appeal")({
  head: () => ({ meta: [
    { title: "Appeal a Workers' Compensation Decision — Authority-First | Appeal Mail" },
    { name: "description", content: "Analyze a workers' compensation decision or notice, verify the controlling state procedure, map evidence gaps, and prepare a human-reviewed response with transparent packet pricing." },
    { property: "og:title", content: "Appeal a Workers' Compensation Decision" },
    { property: "og:description", content: "Authority-first workers' compensation appeal analysis with source verification, evidence mapping, Gemini drafting, validation, pricing, and mailing proof." },
  ], links: [{ rel: "canonical", href: "/workflows/workers-comp-appeal" }] }),
  component: WorkersCompAppealPage,
});

function WorkersCompAppealPage() {
  const [file,setFile]=useState<File|null>(null); const [status,setStatus]=useState(""); const [result,setResult]=useState<any>(null);
  async function analyze(){ if(!file)return; setStatus("Analyzing the workers' compensation notice and separating record facts from state procedure that must be verified…"); const form=new FormData(); form.set("document",file); try{const r=await fetch("/api/workflows/workers-comp-appeal/analyze",{method:"POST",body:form}); const p=await r.json(); if(!r.ok)throw new Error(p.error||"Unable to analyze the notice."); setResult(p); setStatus("Analysis complete. Review authority, evidence gaps, contradictions, and unresolved procedure before drafting.");}catch(e){setStatus(e instanceof Error?e.message:"Unable to analyze the notice.");}}
  return <main className="mx-auto max-w-6xl px-6 py-12">
    <section className="rounded-3xl bg-slate-950 p-8 text-white shadow-xl">
      <p className="text-sm font-semibold uppercase tracking-[0.22em] text-slate-300">Workers' Compensation • Authority-first</p>
      <h1 className="mt-4 max-w-4xl text-4xl font-bold tracking-tight md:text-6xl">Appeal a Workers' Compensation Decision</h1>
      <p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">Start with the insurer, employer, board, or agency notice. The workflow identifies what the record actually says, verifies the controlling state path, maps medical and factual support, stress-tests the response, and shows the exact mailing price before payment.</p>
      <div className="mt-8 grid gap-4 md:grid-cols-3">{[["Authority raised","The notice and current controlling state sources take priority; unsupported deadlines, forums, forms, and filing instructions stay unresolved."],["Evidence-aware","Medical records, wage records, injury facts, disputed findings, contradictions, and missing support are separated rather than invented."],["Transparent pricing","Preparation, response sheets, supporting sheets, mailing method, and packet surcharges are shown before checkout."]].map(([a,c])=><div key={a} className="rounded-2xl border border-white/10 bg-white/5 p-5"><h2 className="font-semibold">{a}</h2><p className="mt-2 text-sm leading-6 text-slate-300">{c}</p></div>)}</div>
    </section>
    <section className="mt-10 grid gap-8 lg:grid-cols-[1.1fr_.9fr]">
      <div className="rounded-3xl border border-slate-200 bg-white p-7"><h2 className="text-2xl font-semibold">What we analyze</h2><ol className="mt-6 space-y-4">{["Identify the issuing authority, injury/claim references, dates, findings, instructions, and cited sources.","Verify the controlling state appeal path and timing against the notice and authoritative sources.","Separate medical, wage, employer, injury, and claim facts from disputed or unsupported statements.","Map evidence gaps and contradictions and stress-test the proposed response before approval.","Require explicit human approval before final packet pricing, payment, and mailing."].map((x,i)=><li key={x} className="flex gap-4"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-slate-900 text-sm font-bold text-white">{i+1}</span><span className="leading-7 text-slate-700">{x}</span></li>)}</ol></div>
      <div className="rounded-3xl border border-slate-200 bg-slate-50 p-7"><h2 className="text-2xl font-semibold">Start with your notice</h2><p className="mt-3 text-sm leading-6 text-slate-600">Starting price: <strong>${WORKERS_COMP_APPEAL_PRICING.preparationFee.toFixed(2)}</strong> plus mailing, assuming {WORKERS_COMP_APPEAL_PRICING.includedResponsePages} response pages and no supporting-document sheets.</p><input className="mt-6 block w-full rounded-xl border border-slate-300 bg-white p-3 text-sm" type="file" accept="application/pdf,image/png,image/jpeg" onChange={e=>setFile(e.target.files?.[0]||null)}/><button className="mt-4 w-full rounded-xl bg-slate-900 px-5 py-3 font-semibold text-white disabled:opacity-40" disabled={!file} onClick={analyze}>Analyze workers' comp notice</button>{status&&<p className="mt-4 text-sm text-slate-600">{status}</p>}{result&&<div className="mt-6 rounded-2xl bg-white p-5"><h3 className="font-semibold">Notice snapshot</h3><dl className="mt-3 space-y-2 text-sm"><div><dt className="inline font-medium">Issuer: </dt><dd className="inline">{result.analysis?.issuer||"Not identified"}</dd></div><div><dt className="inline font-medium">State: </dt><dd className="inline">{result.analysis?.jurisdiction||"Not identified"}</dd></div><div><dt className="inline font-medium">Decision date: </dt><dd className="inline">{result.analysis?.decisionDate||"Not identified"}</dd></div><div><dt className="inline font-medium">Deadline status: </dt><dd className="inline">{result.analysis?.deadlineStatus||"unverified"}</dd></div></dl></div>}</div>
    </section>
    <section className="mt-10 rounded-3xl border border-slate-200 bg-white p-7"><h2 className="text-2xl font-semibold">Transparent pricing</h2><div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[["Preparation",`$${WORKERS_COMP_APPEAL_PRICING.preparationFee.toFixed(2)}`],["Included response",`${WORKERS_COMP_APPEAL_PRICING.includedResponsePages} pages`],["Extra response",`$${WORKERS_COMP_APPEAL_PRICING.responsePagePrice.toFixed(2)}/sheet`],["Supporting evidence",`$${WORKERS_COMP_APPEAL_PRICING.supportingPagePrice.toFixed(2)}/sheet`],["Standard mail",`$${WORKERS_COMP_APPEAL_PRICING.standardMail.toFixed(2)}`],["Certified",`$${WORKERS_COMP_APPEAL_PRICING.certifiedMail.toFixed(2)}`],["Certified + return receipt",`$${WORKERS_COMP_APPEAL_PRICING.certifiedReturnReceipt.toFixed(2)}`],["Flat packet surcharge",`$${WORKERS_COMP_APPEAL_PRICING.flatEnvelopeFee.toFixed(2)} when required`]].map(([a,b])=><div key={a} className="rounded-2xl bg-slate-50 p-4"><div className="text-sm text-slate-500">{a}</div><div className="mt-1 font-semibold">{b}</div></div>)}</div><p className="mt-6 text-sm leading-7 text-slate-600">The exact price is calculated from the approved physical packet. Supporting-document sheets are billed separately when included.</p></section>
    <p className="mt-10 text-sm text-slate-500">Appeal Mail is not a law firm and does not provide legal advice. Workers' compensation rules are state-specific and must be verified against current authoritative sources.</p>
  </main>;
}
