import { createFileRoute } from "@tanstack/react-router";
import { requireAuthenticatedUser, getSupabaseServer } from "@/platform/supabase";
import { uploadDocument } from "@/platform/mailmypdf";

type ProviderConfig = { provider: "anthropic" | "openai" | "gemini"; apiKey: string; model: string; promptOverride?: string | null };
async function resolveProvider() {
  const base = process.env.MAILMYPDF_CONTROL_PLANE_URL || "https://mailmypdf.com"; const token = process.env.MAILMYPDF_CONTROL_PLANE_TOKEN;
  if (!token) throw new Error("MailMyPDF control-plane token is not configured.");
  const res = await fetch(`${base.replace(/\/$/, "")}/api/control-plane/ai`, { method: "POST", headers: { "content-type":"application/json", authorization:`Bearer ${token}` }, body: JSON.stringify({ verticalSlug:"appeal-mail", workflowSlug:"licensing-appeal", task:"analysis" }) });
  const payload = await res.json().catch(()=>null); if(!res.ok) throw new Error(payload?.error || `Control plane error (${res.status}).`); return payload as ProviderConfig;
}
function mediaType(file: File) { if(["application/pdf","image/png","image/jpeg"].includes(file.type)) return file.type; throw new Error("Licensing Appeal accepts PDF, PNG, and JPEG source documents."); }
export const Route = createFileRoute("/api/workflows/licensing-appeal/analyze")({ server:{ handlers:{ POST:async({request})=>{ try {
  const user=await requireAuthenticatedUser(request); const form=await request.formData(); const file=form.get("document");
  if(!(file instanceof File)) return Response.json({error:"A licensing decision is required."},{status:400}); if(file.size===0)return Response.json({error:"The source document is empty."},{status:400}); if(file.size>20*1024*1024)return Response.json({error:"Source documents must be 20 MB or smaller."},{status:413});
  const cfg=await resolveProvider(); if(cfg.provider!=="gemini") throw new Error("Licensing Appeal is currently configured for Gemini."); const sourceDocument=await uploadDocument(file); const bytes=Buffer.from(await file.arrayBuffer()).toString("base64");
  const prompt=cfg.promptOverride||["You are the authority-first analyst for a licensing appeal workflow.","Return strict JSON only. Extract only information supported by the uploaded decision.","Never invent deadlines, board procedures, forms, recipients, filing methods, exhaustion requirements, hearing rights, stay rules, legal rules, facts, or outcomes.","Distinguish license effective/suspension/revocation dates from verified appeal deadlines.",'{"summary":"","issuer":"","license":"","licenseType":"","jurisdiction":"","decisionType":"","referenceNumber":"","decisionDate":"","effectiveDate":"","deadline":"","deadlineStatus":"extracted|verified|unverified","appealInstructions":"","findings":[],"citedAuthority":[],"disciplinaryAllegations":[],"disputedFacts":[],"evidenceMentioned":[],"evidenceGaps":[],"contradictions":[],"uncertainties":[],"authoritySources":[{"claim":"","sourceType":"document|board|agency|court|statute|regulation|rule|other","sourceUrl":"","sourceTitle":"","jurisdiction":"","effectiveDate":"","verificationState":"verified|partially_verified|unverified|conflicting","notes":""}],"confidence":"high|medium|low"}',"Use empty values for unknown information."].join("\n");
  const res=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(cfg.model)}:generateContent?key=${encodeURIComponent(cfg.apiKey)}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({contents:[{role:"user",parts:[{inlineData:{mimeType:mediaType(file),data:bytes}},{text:prompt}]}],generationConfig:{responseMimeType:"application/json",temperature:0.1}})});
  const body=await res.json().catch(()=>null) as any; if(!res.ok)throw new Error(body?.error?.message||`Gemini analysis failed (${res.status}).`); const text=body?.candidates?.[0]?.content?.parts?.map((p:{text?:string})=>p.text||"").join("").trim(); if(!text)throw new Error("Gemini returned no analysis.");
  const analysis=JSON.parse(text) as Record<string,unknown>; const now=new Date().toISOString(); const appealId=crypto.randomUUID();
  const decision={id:crypto.randomUUID(),type:"licensing_decision",documentId:sourceDocument.id,documentFilename:file.name,agency:analysis.issuer||"",license:analysis.license||"",licenseType:analysis.licenseType||"",jurisdiction:analysis.jurisdiction||"",decisionType:analysis.decisionType||"",referenceNumber:analysis.referenceNumber||"",decisionDate:analysis.decisionDate||"",effectiveDate:analysis.effectiveDate||"",deadline:analysis.deadline?{date:analysis.deadline,status:analysis.deadlineStatus||"unverified",source:"extracted"}:undefined,findings:Array.isArray(analysis.findings)?analysis.findings:[],citedAuthority:Array.isArray(analysis.citedAuthority)?analysis.citedAuthority:[],disciplinaryAllegations:Array.isArray(analysis.disciplinaryAllegations)?analysis.disciplinaryAllegations:[],disputedFacts:Array.isArray(analysis.disputedFacts)?analysis.disputedFacts:[],evidenceGaps:Array.isArray(analysis.evidenceGaps)?analysis.evidenceGaps:[],contradictions:Array.isArray(analysis.contradictions)?analysis.contradictions:[],authoritySources:Array.isArray(analysis.authoritySources)?analysis.authoritySources:[],uncertainties:Array.isArray(analysis.uncertainties)?analysis.uncertainties:[],appealInstructions:analysis.appealInstructions||"",extractedAt:now};
  const supabase=await getSupabaseServer(); const {error}=await supabase.from("appeals").insert({id:appealId,user_id:user.id,workflow_id:"licensing-appeal",status:"in_progress",decision,grounds:[],evidence:[{id:crypto.randomUUID(),type:"document",label:file.name,documentId:sourceDocument.id,uploadedAt:now}],arguments:[],draft:"",review:null,packet:null,proof:null,timeline:[],version:1,created_at:now,updated_at:now}); if(error)throw new Error(`Unable to save appeal: ${error.message}`);
  return Response.json({ok:true,appealId,documentId:sourceDocument.id,analysis,provider:"gemini",model:cfg.model});
 } catch(error){const message=error instanceof Error?error.message:"Unable to analyze licensing decision.";return Response.json({error:message},{status:/authentication|required|token/i.test(message)?401:502});} } } });
