/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppealADecisionRouteImport } from './routes/appeal-a-decision'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as AppealSlugRouteImport } from './routes/appeal/$slug'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ResourcesSlugRouteImport } from './routes/resources/$slug'
import { Route as WorkflowsCourtRulingRouteImport } from './routes/workflows/court-ruling'
import { Route as WorkflowsDeniedClaimRouteImport } from './routes/workflows/denied-claim'
import { Route as WorkflowsGovernmentDecisionRouteImport } from './routes/workflows/government-decision'
import { Route as WorkflowsReconsiderationRouteImport } from './routes/workflows/reconsideration'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealADecisionRoute = AppealADecisionRouteImport.update({
  id: '/appeal-a-decision',
  path: '/appeal-a-decision',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealSlugRoute = AppealSlugRouteImport.update({
  id: '/appeal/$slug',
  path: '/appeal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsCourtRulingRoute = WorkflowsCourtRulingRouteImport.update({
  id: '/court-ruling',
  path: '/court-ruling',
  getParentRoute: () => WorkflowsRoute,
} as any)
const WorkflowsDeniedClaimRoute = WorkflowsDeniedClaimRouteImport.update({
  id: '/denied-claim',
  path: '/denied-claim',
  getParentRoute: () => WorkflowsRoute,
} as any)
const WorkflowsGovernmentDecisionRoute =
  WorkflowsGovernmentDecisionRouteImport.update({
    id: '/government-decision',
    path: '/government-decision',
    getParentRoute: () => WorkflowsRoute,
  } as any)
const WorkflowsReconsiderationRoute =
  WorkflowsReconsiderationRouteImport.update({
    id: '/reconsideration',
    path: '/reconsideration',
    getParentRoute: () => WorkflowsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appeal-a-decision': typeof AppealADecisionRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/appeal/$slug': typeof AppealSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/workflows/court-ruling': typeof WorkflowsCourtRulingRoute
  '/workflows/denied-claim': typeof WorkflowsDeniedClaimRoute
  '/workflows/government-decision': typeof WorkflowsGovernmentDecisionRoute
  '/workflows/reconsideration': typeof WorkflowsReconsiderationRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appeal-a-decision': typeof AppealADecisionRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/appeal/$slug': typeof AppealSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/workflows/court-ruling': typeof WorkflowsCourtRulingRoute
  '/workflows/denied-claim': typeof WorkflowsDeniedClaimRoute
  '/workflows/government-decision': typeof WorkflowsGovernmentDecisionRoute
  '/workflows/reconsideration': typeof WorkflowsReconsiderationRoute
  '/resources': typeof ResourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appeal-a-decision': typeof AppealADecisionRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/appeal/$slug': typeof AppealSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/workflows/court-ruling': typeof WorkflowsCourtRulingRoute
  '/workflows/denied-claim': typeof WorkflowsDeniedClaimRoute
  '/workflows/government-decision': typeof WorkflowsGovernmentDecisionRoute
  '/workflows/reconsideration': typeof WorkflowsReconsiderationRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/appeal-a-decision'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/workflows'
    | '/appeal/$slug'
    | '/resources/$slug'
    | '/workflows/court-ruling'
    | '/workflows/denied-claim'
    | '/workflows/government-decision'
    | '/workflows/reconsideration'
    | '/resources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/appeal-a-decision'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/workflows'
    | '/appeal/$slug'
    | '/resources/$slug'
    | '/workflows/court-ruling'
    | '/workflows/denied-claim'
    | '/workflows/government-decision'
    | '/workflows/reconsideration'
    | '/resources'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/appeal-a-decision'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/workflows'
    | '/appeal/$slug'
    | '/resources/$slug'
    | '/workflows/court-ruling'
    | '/workflows/denied-claim'
    | '/workflows/government-decision'
    | '/workflows/reconsideration'
    | '/resources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppealADecisionRoute: typeof AppealADecisionRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  WorkflowsRoute: typeof WorkflowsRouteWithChildren
  AppealSlugRoute: typeof AppealSlugRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeal-a-decision': {
      id: '/appeal-a-decision'
      path: '/appeal-a-decision'
      fullPath: '/appeal-a-decision'
      preLoaderRoute: typeof AppealADecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeal/$slug': {
      id: '/appeal/$slug'
      path: '/appeal/$slug'
      fullPath: '/appeal/$slug'
      preLoaderRoute: typeof AppealSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/court-ruling': {
      id: '/workflows/court-ruling'
      path: '/court-ruling'
      fullPath: '/workflows/court-ruling'
      preLoaderRoute: typeof WorkflowsCourtRulingRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/denied-claim': {
      id: '/workflows/denied-claim'
      path: '/denied-claim'
      fullPath: '/workflows/denied-claim'
      preLoaderRoute: typeof WorkflowsDeniedClaimRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/government-decision': {
      id: '/workflows/government-decision'
      path: '/government-decision'
      fullPath: '/workflows/government-decision'
      preLoaderRoute: typeof WorkflowsGovernmentDecisionRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/reconsideration': {
      id: '/workflows/reconsideration'
      path: '/reconsideration'
      fullPath: '/workflows/reconsideration'
      preLoaderRoute: typeof WorkflowsReconsiderationRouteImport
      parentRoute: typeof WorkflowsRoute
    }
  }
}

interface WorkflowsRouteChildren {
  WorkflowsCourtRulingRoute: typeof WorkflowsCourtRulingRoute
  WorkflowsDeniedClaimRoute: typeof WorkflowsDeniedClaimRoute
  WorkflowsGovernmentDecisionRoute: typeof WorkflowsGovernmentDecisionRoute
  WorkflowsReconsiderationRoute: typeof WorkflowsReconsiderationRoute
}

const WorkflowsRouteChildren: WorkflowsRouteChildren = {
  WorkflowsCourtRulingRoute: WorkflowsCourtRulingRoute,
  WorkflowsDeniedClaimRoute: WorkflowsDeniedClaimRoute,
  WorkflowsGovernmentDecisionRoute: WorkflowsGovernmentDecisionRoute,
  WorkflowsReconsiderationRoute: WorkflowsReconsiderationRoute,
}

const WorkflowsRouteWithChildren = WorkflowsRoute._addFileChildren(
  WorkflowsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppealADecisionRoute: AppealADecisionRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  WorkflowsRoute: WorkflowsRouteWithChildren,
  AppealSlugRoute: AppealSlugRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
